sudo: false
language: java
jdk: 
  - oraclejdk8
# noop to override travis default
install: true
script:
  - mvn clean package jacoco:report site -B -V -Dgithub.global.userName=${github_username} -Dgithub.global.password=${github_password}
